#!/usr/bin/env bash
# Copyright 2014-2023 Scalyr Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -e

DEPENDENCIES_ROOT="/opt/scalyr-agent-2-dependencies"

EXECUTABLE="${1}"
shift
OPENSSL_INIT_SNIPPET="${1}"
shift

# shellcheck source=/dev/null
source "${OPENSSL_INIT_SNIPPET}"

DEPENDENCIES_LIB_DIR="${DEPENDENCIES_ROOT}/lib"

if $IS_EMBEDDED ; then
  LD_LIBRARY_PATH="${DEPENDENCIES_LIB_DIR}/openssl/${OPENSSL_VARIANT}:${LD_LIBRARY_PATH}"
fi

export LD_LIBRARY_PATH="${DEPENDENCIES_LIB_DIR}:${LD_LIBRARY_PATH}"

exec "${EXECUTABLE}" "$@"
